services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain_agriculture_api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    depends_on:
      - db 
    volumes:
      - .:/usr/src/app  

  db:
    image: postgres:13  
    container_name: brain_agriculture_db
    ports:
      - "5432:5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: